[whisper]
record_timeout = 2
phrase_timeout = 3

[uart]
; how many times to attempt to read model output when current work string is too short
max_retry = 3
; how long to wait between retries (in seconds, as float)
retry_time = 0.25
; whether to use Pisarz Internal Communication Protocol
use_picp = false
; frame_size is used only if PICP is not used
frame_size = 4
; COM port to be used
COM_port = COM5

[log]
; valid log levels from lowest to highest are:
; {TRACE, DEBUG, INFO, WARNING, ERROR}
level = DEBUG
dump  = true
log_path = ./.logs/
; if log_all is enabled, every log message will be dumped to a separate file regardless of log_level
; wrong log level messages will still be suppressed in the main log file and standard output
log_all = true